# @package _global_
defaults:
  - /trainer: default
  - /loader: default
  - /dataset: clinvar
  - /task: multiclass_classification
  - /optimizer: adamw
  - /scheduler: plateau
  - /callbacks: [base, checkpoint]

train:
  monitor: val/loss # Needed for plateau scheduler
  mode: min

encoder: id

# we need this for classification!
decoder:
  _name_: sequence
  mode: pool
