# @package _global_
defaults:
  - /trainer: default
  - /loader: default
  - /dataset: viral
  - /optimizer: adamw
  - /scheduler: cosine_warmup
  - /callbacks: [base, checkpoint]

train:
  monitor: test/loss
  mode: min

task:
  _name_: lm
  loss: 
    _name_: cross_entropy
    ignore_index: 4
  torchmetrics: ['perplexity', 'num_tokens']

encoder: null
decoder: null
