_name_: clinvar
max_length: 1024
use_padding: True
padding_side: 'left'
add_eos: False
batch_size: 32
shuffle: true  # set this as default!
train_len: ${div_up:1_000_000_000, ${.max_length}}
__l_max: ${.max_length}