# _target_: tasks.tasks.MultiClass
_name_: multiclass
loss: cross_entropy
metrics:
  - accuracy_per_class
  - roc_auc_macro
  - f1_binary
# torchmetrics:
#   - AUROC
#   - Precision
#   - Recall
#   - F1Score
